name: fake_store
description: "FakeStore is a Flutter e-commerce app that integrates with the FakeStoreApi, providing product management, user lists, shopping carts, and authentication, delivering a full-featured online shopping experience."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  collection: ^1.17.0
  fake_store_api_package:
    git:
      url: https://github.com/Maullin1996/fake_store_api_package.git
      ref: main
  fake_store_design:
    git:
      url: https://github.com/Maullin1996/fake_store_design.git
      ref: main
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1

dev_dependencies:
  dart_code_linter: ^2.0.0
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  riverpod_test: ^0.1.9
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
