name: fake_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  collection: ^1.17.0
  fake_store_api_package:
    git:
      url: https://github.com/Maullin1996/fake_store_api_package.git
      ref: main
  fake_store_design:
    path: E:/Archivos/movile_apps/practicing/phase_4/fake_store_design
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  dart_code_linter: ^2.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
