// Mocks generated by Mockito 5.4.5 from annotations
// in fake_store/test/unit_test/presentation/providers/api_response/products_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:fake_store/domain/services/key_value_storage_service.dart'
    as _i8;
import 'package:fake_store_api_package/errors/index_errors.dart' as _i3;
import 'package:fake_store_api_package/infraestructure/driven-adapter/api/fake_store_api.dart'
    as _i4;
import 'package:fake_store_api_package/infraestructure/helppers/mappers.dart'
    as _i7;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiErrorHandler_1 extends _i1.SmartFake
    implements _i3.ApiErrorHandler {
  _FakeApiErrorHandler_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiFailure_2 extends _i1.SmartFake implements _i3.ApiFailure {
  _FakeApiFailure_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FakeStoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeStoreApi extends _i1.Mock implements _i4.FakeStoreApi {
  MockFakeStoreApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i3.ApiErrorHandler get errorHandler => (super.noSuchMethod(
        Invocation.getter(#errorHandler),
        returnValue: _FakeApiErrorHandler_1(
          this,
          Invocation.getter(#errorHandler),
        ),
      ) as _i3.ApiErrorHandler);

  @override
  _i6.Future<List<_i7.ProductsFakeStore>> fetchProducts(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [endpoint],
        ),
        returnValue: _i6.Future<List<_i7.ProductsFakeStore>>.value(
            <_i7.ProductsFakeStore>[]),
      ) as _i6.Future<List<_i7.ProductsFakeStore>>);

  @override
  _i6.Future<List<_i7.CartsFakeStore>> fetchCart(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCart,
          [endpoint],
        ),
        returnValue:
            _i6.Future<List<_i7.CartsFakeStore>>.value(<_i7.CartsFakeStore>[]),
      ) as _i6.Future<List<_i7.CartsFakeStore>>);

  @override
  _i6.Future<List<_i7.UsersFakeStore>> fetchUser(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUser,
          [endpoint],
        ),
        returnValue:
            _i6.Future<List<_i7.UsersFakeStore>>.value(<_i7.UsersFakeStore>[]),
      ) as _i6.Future<List<_i7.UsersFakeStore>>);
}

/// A class which mocks [ApiErrorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiErrorHandler extends _i1.Mock implements _i3.ApiErrorHandler {
  MockApiErrorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiFailure handle(dynamic error) => (super.noSuchMethod(
        Invocation.method(
          #handle,
          [error],
        ),
        returnValue: _FakeApiFailure_2(
          this,
          Invocation.method(
            #handle,
            [error],
          ),
        ),
      ) as _i3.ApiFailure);
}

/// A class which mocks [KeyValueStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyValueStorageService extends _i1.Mock
    implements _i8.KeyValueStorageService {
  MockKeyValueStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> setKeyValue<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setKeyValue,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<T?> getValue<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [key],
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<bool> removeKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeKey,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [FakeStoreApi].
///
/// See the documentation for Mockito's code generation for more information.
class GeneratedMockFakeStoreApi extends _i1.Mock implements _i4.FakeStoreApi {
  GeneratedMockFakeStoreApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i3.ApiErrorHandler get errorHandler => (super.noSuchMethod(
        Invocation.getter(#errorHandler),
        returnValue: _FakeApiErrorHandler_1(
          this,
          Invocation.getter(#errorHandler),
        ),
      ) as _i3.ApiErrorHandler);

  @override
  _i6.Future<List<_i7.ProductsFakeStore>> fetchProducts(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [endpoint],
        ),
        returnValue: _i6.Future<List<_i7.ProductsFakeStore>>.value(
            <_i7.ProductsFakeStore>[]),
      ) as _i6.Future<List<_i7.ProductsFakeStore>>);

  @override
  _i6.Future<List<_i7.CartsFakeStore>> fetchCart(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCart,
          [endpoint],
        ),
        returnValue:
            _i6.Future<List<_i7.CartsFakeStore>>.value(<_i7.CartsFakeStore>[]),
      ) as _i6.Future<List<_i7.CartsFakeStore>>);

  @override
  _i6.Future<List<_i7.UsersFakeStore>> fetchUser(String? endpoint) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUser,
          [endpoint],
        ),
        returnValue:
            _i6.Future<List<_i7.UsersFakeStore>>.value(<_i7.UsersFakeStore>[]),
      ) as _i6.Future<List<_i7.UsersFakeStore>>);
}

/// A class which mocks [ApiErrorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class GeneratedMockApiErrorHandler extends _i1.Mock
    implements _i3.ApiErrorHandler {
  GeneratedMockApiErrorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiFailure handle(dynamic error) => (super.noSuchMethod(
        Invocation.method(
          #handle,
          [error],
        ),
        returnValue: _FakeApiFailure_2(
          this,
          Invocation.method(
            #handle,
            [error],
          ),
        ),
      ) as _i3.ApiFailure);
}

/// A class which mocks [KeyValueStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class GeneratedMockKeyValueStorage extends _i1.Mock
    implements _i8.KeyValueStorageService {
  GeneratedMockKeyValueStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> setKeyValue<T>(
    String? key,
    T? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setKeyValue,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<T?> getValue<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getValue,
          [key],
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<bool> removeKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeKey,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
